name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    environment: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Grant execute permission for build script
      run: chmod +x ./scripts/build.sh
    - name: Build with Gradle
      run: ./gradlew build --args='-Pwhitelotus_storePassword=$WHITELOTUS_STOREPASSWORD -Pwhitelotus_keyAlias=$WHITELOTUS_KEYALIAS -Pwhitelotus_keyPassword=$WHITELOTUS_KEYPASSWORD'
